search_space:
  model:
    network:
      init_args:
        d_model:
          distribution: categorical
          choices: [128, 256]
        e_layers:
          distribution: int
          low: 2
          high: 4
          step: 1
        dropout:
          distribution: uniform
          low: 0.0
          high: 0.2
          step: 0.1
        top_k_limit:
          distribution: categorical
          choices: [64, 128, 256]
        token_kernel_size:
          distribution: categorical
          choices: [3, 5]
    detector:
      init_args:
        rank_threshold:
          distribution: loguniform
          low: 1.0e-3
          high: 1.0e-1
    losses:
      init_args:
        lambda_reg:
          distribution: loguniform
          low: 1.0
          high: 10.0
    optimizer:
      init_args:
        lr:
          distribution: loguniform
          low: 1.0e-4
          high: 1.0e-3
  window_size:
    distribution: categorical
    choices: [64, 100, 128]
