search_space:
  model:
    optimizer:
      init_args:
        lr:
          distribution: loguniform
          low: 1e-4
          high: 1e-2
    network:
      num_trans:
        distribution: int
        low: 2
        high: 6
        step: 2
      trans_type:
        distribution: categorical
        choices: ["forward", "mul", "residual"]
      enc_hdim:
        distribution: int
        low: 32
        high: 128
        step: 32
      enc_nlayers:
        distribution: int
        low: 1
        high: 4
      trans_nlayers:
        distribution: int
        low: 1
        high: 4
      latent_dim:
        distribution: int
        low: 32
        high: 128
        step: 32
      batch_norm:
        distribution: categorical
        choices: [true, false]
      enc_bias:
        distribution: categorical
        choices: [ true, false ]
      use_invertible_transforms:
        distribution: categorical
        choices: [ true, false ]
      use_group_transforms:
        distribution: categorical
        choices: [ true, false ]
      use_freq_ortho_transforms:
        distribution: categorical
        choices: [ true, false ]
      encoder_type:
        distribution: categorical
        choices: [ "base", "patchtst", "itransformer" ]
      pooling:
        distribution: categorical
        choices: [ "base", "mean", "meanmax", "attn" ]
      proj_head:
        distribution: categorical
        choices: [ "base", "linear", "mlp", "identity", "none" ]
    losses:
      init_args:
        use_euclidean:
          distribution: categorical
          choices: [true, false]
  window_size:
    distribution: int
    low: 8
    high: 128
    step: 10
