model:
  network:
    class_path: noboom_benchmark.noboom_lib.core.models.catch_paper_neural.ITransformer
    init_args:
      input_dim: null
      seq_len: null
      d_model: 128
      e_layers: 1
      n_heads: 4
      d_ff: 256
      dropout: 0.1
      activation: gelu
  detector:
    class_path: noboom_benchmark.noboom_lib.core.models.catch_paper_neural.NeuralReconstructionAnomalyDetector
    init_args:
      seq_len: null
      batch_size: 128
      reduce_to_last_step: true
  losses:
    class_path: noboom_benchmark.noboom_lib.core.models.catch_paper_neural.NeuralReconstructionLoss
  optimizer:
    class_path: torch.optim.AdamW
    init_args:
      lr: 1.0e-3
  compile_torch_model: true
  compile_torch_model_mode: max-autotune-no-cudagraphs
  compile_torch_model_fullgraph: false
trainer:
  precision: bf16-mixed
  max_epochs: 3
  check_val_every_n_epoch: 1
data:
  batch_dim: 0
  train_transform:
    - class_path: timesead.data.transforms.WindowTransformIfNotWindow
      init_args:
        window_size: null
    - class_path: timesead.data.transforms.ReconstructionTargetTransform
      init_args:
        replace_labels: true
  val_transform:
    - class_path: timesead.data.transforms.WindowTransformIfNotWindow
      init_args:
        window_size: null
    - class_path: timesead.data.transforms.ReconstructionTargetTransform
      init_args:
        replace_labels: true
  test_transform:
    - class_path: timesead.data.transforms.WindowTransformIfNotWindow
      init_args:
        window_size: null
    - class_path: timesead.data.transforms.ReconstructionTargetTransform
      init_args:
        replace_labels: false
