model:
  detector:
    class_path: noboom_benchmark.noboom_lib.core.models.detectors.PCAAD
    init_args:
      n_components: 0.95
      svd_solver: full
      whiten: false
      random_state: 42
trainer:
  accelerator: cpu
  max_epochs: 0

data:
  batch_dim: 0
